FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster \
    dagster-webserver \
    dagster-postgres \
    dagster-dbt \
    dbt-postgres

COPY docker/dagster.yaml /opt/dagster/dagster_home/dagster.yaml
COPY docker/workspace.yaml /opt/dagster/dagster_home/workspace.yaml

ENV DAGSTER_HOME=/opt/dagster/dagster_home

WORKDIR /opt/dagster/dagster_home
