dagster_dbt_demo:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dagster') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'dagster_password') }}"
      dbname: "{{ env_var('WAREHOUSE_DB', 'warehouse') }}"
      schema: public
      threads: 4
